lecture_code/DJANGO_BLOG/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('password/', views.change_password, name='change_password'),
    path('edit/', views.edit, name='edit'),
    path('quit/', views.quit, name='quit'),
    path('logout/', views.logout, name='logout'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
]

lecture_code/DJANGO_BLOG/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('<int:article_id>/comments/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:article_id>/comments/', views.comment_create, name='comment_create'),
    path('<int:article_id>/delete/', views.delete, name='delete'),
    path('<int:article_id>/update/', views.update, name='update'),
    # path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:article_id>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    # path('new/', views.new, name='new'),
    path('', views.index, name='index'),
]

lecture_code/DJANGO_BLOG/django_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('jobs/', include('jobs.urls')),
    path('students/', include('students.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lecture_code/DJANGO_BLOG/jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'

urlpatterns = [
    path('', views.index, name='index'),
    path('past_life/', views.past_life, name='past_life'),
]

lecture_code/DJANGO_BLOG/articles/models.py
from django.db import models
from django.conf import settings
# from imagekit.models import ProcessedImageField
# from imagekit.processors import ResizeToFill, Thumbnail

class Article(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    image = models.ImageField(blank=True)
    # image = ProcessedImageField(                # Win7 OSError issue 로 Win10 이나 Mac 에서만 해주시는걸로..ㅠㅠ
    #     upload_to = 'articles/images',          # 저장 위치(MEDIA_ROOT/articles/images)
    #     processors = [ResizeToFill(200, 300)],  # 처리할 작업 목록
    #     format = 'jpeg',                        # 저장 포맷
    #     options = {'quality':90},               # 추가 옵션
    # )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.id}번 글 - {self.title} : {self.content}'

class Comment(models.Model):
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    def __str__(self):
        return f'<Article({self.article_id}) : Comment({self.id})> - {self.content}'

lecture_code/DJANGO_BLOG/articles/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title','content','image',]

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content',]

lecture_code/DJANGO_BLOG/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article, Comment
from .forms import ArticleForm, CommentForm
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required

def index(request):
    articles = Article.objects.order_by('-pk')
    # articles = Article.objects.all()[::-1]
    return render(request, 'articles/index.html', {'articles':articles})

# def new(request):
#     return render(request, 'articles/new.html')

@login_required
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('articles:detail', article.id)
        # title = request.POST.get('title')
        # content = request.POST.get('content')
        # image = request.FILES.get('image')
        # article = Article(title=title, content=content, image=image)
        # article.save()
        # return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm()
        return render(request, 'articles/form.html', {'form':form})


def detail(request, article_id):
    # article = Article.objects.get(pk=article_id)
    article = get_object_or_404(Article, pk=article_id)
    comments = article.comment_set.all()
    comment_form = CommentForm()
    return render(request, 'articles/detail.html', {'article':article, 'comments':comments, 'comment_form':comment_form})

@login_required
@require_POST
def delete(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    if article.user == request.user:
    # article = Article.objects.get(pk=article_id)
    # if request.method == 'POST':
        article.delete()
    return redirect('articles:index')
    # else:
    #     return redirect('articles:detail', article.pk)

# def edit(request, pk):
#     article = Article.objects.get(pk=pk)
#     return render(request, 'articles/edit.html', {'article':article})

@login_required
def update(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    # article = Article.objects.get(pk=article_id)
    if article.user == request.user:
        if request.method == 'POST':
            form = ArticleForm(request.POST, request.FILES, instance=article)
            if form.is_valid():
                article = form.save()
                return redirect('articles:detail', article.id)
            # article.title = request.POST.get('title')
            # article.content = request.POST.get('content')
            # article.image = request.FILES.get('image')
            # article.save()
            # return redirect('articles:detail', article.pk)
        else:
            form = ArticleForm(instance=article)
    else:
        return redirect('articles:index')
    return render(request, 'articles/form.html', {'form':form, 'article':article})

@require_POST
def comment_create(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    # article = Article.objects.get(pk=article_id)
    comment_form = CommentForm(request.POST)
    # if request.method == 'POST':
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.article = article
        comment.user = request.user
        comment.save()
    return redirect('articles:detail', article.id)
        # comment = Comment()
        # comment.content = request.POST.get('content')
        # comment.article = article
        # comment.save()
    #     return redirect('articles:detail', article.id)
    # else:
    #     return redirect('articles:detail', article.id)
    # return redirect('articles:detail', article_id)

@require_POST
def comment_delete(request, article_id, comment_id):
    # if request.method == 'POST':
    comment = Comment.objects.get(pk=comment_id)
    comment.delete()
    return redirect('articles:detail', article_id)

lecture_code/DJANGO_BLOG/articles/templates/articles/base.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'articles/favicon/favicon-16x16.png' %}">
    <title>My_Blog</title>
</head>
<body>
    <div class="container">
        <!-- {% if user.is_authenticated %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'articles:index' %}">Welcome {{ user.username }}</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">        
                <form action="{% url 'accounts:logout' %}" method="POST" style='display:inline'>
                    {% csrf_token %}
                    <input class='nav-item nav-link border-0 bg-transparent' type="submit" value="/ 로그아웃">
                </form>
                <form action="{% url 'accounts:quit' %}" method='POST' style='display:inline'>
                    {% csrf_token %}
                    <input class='nav-item nav-link border-0 bg-transparent' type="submit" value="/ 회원탈퇴">
                </form>   
                </div>
            </div>
        </nav>
        {% else %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'articles:index' %}">Welcome Juan's Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">        
                <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">/ 회원가입</a>
                <a class="nav-item nav-link" href="{% url 'accounts:login' %}">/ 로그인</a>        
                </div>
            </div>
        </nav>
        {% endif %} -->
        {% if user.is_authenticated %}
        <h1>Hello! {{ user.username }}!</h1>
        <a href="{% url 'accounts:edit' %}"><button class='btn btn-success btn-sm'>회원정보 수정</button></a>
        <a href="{% url 'accounts:change_password' %}"><button class='btn btn-success btn-sm'>비밀번호 변경</button></a>
        <form action="{% url 'accounts:logout' %}" method="POST" style='display:inline'>
            {% csrf_token %}
            <button class='btn btn-success btn-sm'>로그아웃</button>
        </form>
        <form action="{% url 'accounts:quit' %}" method='POST' style='display:inline'>
            {% csrf_token %}
            <button class='btn btn-secondary btn-sm'>회원탈퇴</button>
        </form>
        {% else %}
        <h1>Hello! Stranger~!</h1>
        <a href="{% url 'accounts:signup' %}"><button class='btn btn-success btn-sm'>회원가입</button></a>
        <a href="{% url 'accounts:login' %}"><button class='btn btn-success btn-sm'>로그인</button></a>
        {% endif %}
        {% block body %}        
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

lecture_code/DJANGO_BLOG/articles/templates/articles/create.html
{% extends 'articles/base.html' %}

{% block title %}CREATE{% endblock %}
{% block body %}
    <h1 class='text-center'>성공적으로 작성되었습니다.</h1>
{% endblock %}

lecture_code/DJANGO_BLOG/articles/templates/articles/detail.html
{% extends 'articles/base.html' %}
{% load static %}
{% load bootstrap4 %} 

{% block title %}DETAIL{% endblock %}
{% block body %}
    <!-- <div class="container">
        <div class="jumbotron jumbotron-fluid bg-secondary">
            <div class="container">
                <h1 class="display-4 text-white">DETAIL</h1>
                <p class="lead font-italic">This is Article</p>
            </div>
        </div>
    </div> -->
    <h1 class='text-center'>DETAIL</h1>
    <h2>{{ article.pk }}번 글</h2>
    <p>작성자: {{ article.user }}</p>
    <hr>
    <p>제목: {{ article.title }}</p>
    <p>내용: {{ article.content }}</p>
    {% if article.image %}
    <p>이미지: <img src="{{ article.image.url }}" alt="{{ article.image }}" width='300px'></p>
    {% else %}
    <p>이미지: <img src="{% static 'articles/images/no_image.jpg' %}" alt="no_image"></p>
    {% endif %}
    <p>작성시간: {{ article.created_at }}</p>
    <p>수정시간: {{ article.updated_at }}</p>
    <hr>
    <p><b>댓글 작성</b></p>
    {% if user.is_authenticated %}
    <form action="{% url 'articles:comment_create' article.id %}" method="POST">
        {% csrf_token %}
        {% bootstrap_form comment_form layout='horizontal' %}
        {% bootstrap_button "등록" button_class='btn btn-primary' %}
        <!-- 댓글 입력: <input type="text" name='content'>
        <input type="submit" value="입력"> -->
    </form>
    {% else %}
    <div class="text-center">
        <a class="btn btn-warning" href="{% url 'accounts:login' %}" role="button">댓글을 작성하려면 로그인 해주세요</a>
    </div>
    {% endif %}
    <hr>    
    <p><b>댓글 목록 | 현재 댓글수: {{ comments|length }}</b></p>
    {% for comment in comments %}
    <ul>
        <li>
            {{ comment.content }} - 
            <form action="{% url 'articles:comment_delete' article.id comment.id %}" style="display: inline;" method = "POST">
                {% csrf_token %}
                <button class='btn btn-secondary btn-sm'>삭제</button>
            </form>
        </li>
    </ul>
    {% empty %}
    <p>댓글이 아직 없습니다.</p>
    {% endfor %}
    <hr>
    {% if article.user == request.user %}
    <a href="{% url 'articles:update' article.pk %}" class="btn btn-dark" style="display:inline;">수정</a>
    <!-- <a href="{% url 'articles:delete' article.pk %}">[DELETE]</a> <br> -->
    <form action="{% url 'articles:delete' article.pk %}" onclick="return confirm('R U Sure..??')" method='POST' style="display:inline;">
        {% csrf_token %}
        <button class='btn btn-dark'>삭제</button>
    </form>
    {% endif %}
    <a href="{% url 'articles:index' %}" class="btn btn-dark" style="display:inline;">목록</a>
{% endblock %}

lecture_code/DJANGO_BLOG/articles/templates/articles/edit.html
{% extends 'articles/base.html' %}
{% load static %}

{% block title %}EDIT{% endblock %}
{% block body %}
    <h1 class='text-center'>EDIT</h1>
    {% if article.image %}
    기존 이미지: <img src="{{ article.image.url }}" alt="{{ article.image }}">
    {% else %}
    기존 이미지: <img src="{% static 'articles/images/no_image.jpg' %}" alt="no_image">
    {% endif %}
    <form action="/articles/{{ article.pk}}/update/" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        제목: <input type="text" name="title" value="{{ article.title }}"> <br>
        내용: <textarea name="content" id="" cols="30" rows="10">{{ article.content }}</textarea> <br>
        이미지: <input type="file" name='image' accept="image/*">
        <input type="submit">
    </form>
    <hr>
    <a href="/articles/{{ article.pk }}/">[뒤로가기]</a>
{% endblock %}

lecture_code/DJANGO_BLOG/articles/templates/articles/form.html
{% extends 'articles/base.html' %}
{% load bootstrap4 %}

<!-- {% block title %}NEW{% endblock %} -->
{% block body %}
    <div class="container">
        <div class="jumbotron jumbotron-fluid bg-secondary">
            <div class="container">
                {% if request.resolver_match.url_name == 'create' %}
                    <h1 class="display-4 text-white">NEW</h1>
                    <p class="lead font-italic">Create a New Article</p>
                {% else %}
                    <h1 class="display-4 text-white">EDIT</h1>
                    <p class="lead font-italic">Edit your Article</p>
                {% endif %}                
            </div>
        </div>
    </div>
    <!-- {% if request.resolver_match.url_name == 'create' %}
    <h1 class='text-center'>NEW</h1>
    {% else %}
    <h1 class='text-center'>EDIT</h1>
    {% endif %} -->
    <form action="" method="POST" enctype="multipart/form-data" style='display:inline'>
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% bootstrap_button "등록" button_class='btn btn-primary' %}
        <!-- 제목: <input type="text" name="title"> <br>
        내용: <textarea name="content" id="" cols="30" rows="10"></textarea> <br>
        이미지: <input type="file" name="image" accept="image/*">
        <input type="submit"> -->
    </form>
    {% if request.resolver_match.url_name == 'create' %}
    <a href="{% url 'articles:index' %}" style='display:inline'><button class='btn btn-dark'>뒤로가기</button></a>
    {% else %}
    <a href="{% url 'articles:detail' article.id %}" style='display:inline'><button class='btn btn-dark'>뒤로가기</button></a>
    {% endif %}
{% endblock %}

lecture_code/DJANGO_BLOG/articles/templates/articles/index.html
{% extends 'articles/base.html' %}
{% load static %}
{% load bootstrap4 %}

<!-- {% block title %}CRUD{% endblock %} -->
{% block body %}
    <!-- <div class="container">
        <div class="jumbotron bg-secondary">
            <h1 class="display-4 text-white">Juan's BOARD</h1>
            <p class="lead">This is My Board</p>
            <hr class="my-4">
            <p class="font-italic">Whatever you want to say</p>
            {% if user.is_authenticated %}
            <a class="btn btn-warning btn-lg" href="{% url 'articles:create' %}" role="button">새 글</a>
            {% else %}
            <a class="btn btn-warning btn-lg" href="{% url 'accounts:login' %}" role="button">로그인 해주세요</a>
            {% endif %}
        </div>
    </div> -->
    <h1 class='text-center'>Articles</h1>
    <img src="{% static 'images/sky.jpg' %}" alt="sample" width='930px' height='200px'><br>
    {% if user.is_authenticated %}
    <a href="{% url 'articles:create' %}">[새글 작성]</a>
    {% else %}
    <a href="{% url 'accounts:login' %}">[새 글을 작성하려면 로그인하세요]</a>
    {% endif %}
    <hr>
    {% for article in articles %}
        <ul>
            <li>No.{{ article.pk }} : <a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a> | 작성자: {{ article.user }}</li>
            <!-- <p>글 제목: {{ article.title }}</p> -->
            <!-- <p>글 내용: {{ article.content }}</p> -->
            <!-- 글 제목: <a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a> -->
        </ul>   
        <hr>
    {% endfor %}
{% endblock %}