lecture_code/DJANGO_BLOG/django_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('jobs/', include('jobs.urls')),
    path('students/', include('students.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lecture_code/DJANGO_BLOG/jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'

urlpatterns = [
    path('', views.index, name='index'),
    path('past_life/', views.past_life, name='past_life'),
]

lecture_code/DJANGO_BLOG/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    # path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    # path('new/', views.new, name='new'),
    path('', views.index, name='index'),
]

lecture_code/DJANGO_BLOG/movies/models.py
from django.db import models

class Movie(models.Model):
    title = models.CharField(max_length=20)
    title_en = models.CharField(max_length=50)
    audience = models.IntegerField()
    open_date = models.DateField()
    genre = models.CharField(max_length=20)
    watch_grade = models.CharField(max_length=10)
    score = models.FloatField()
    poster_url = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return f'{self.title}: {self.score}'

lecture_code/DJANGO_BLOG/movies/views.py
from django.shortcuts import render, redirect
from .models import Movie

def index(request):
    # movies = Movie.objects.all()
    movies = Movie.objects.order_by('-pk')
    return render(request, 'movies/index.html', {'movies':movies})

# def new(request):
#     return render(request, 'movies/new.html')

def create(request):
    if request.method == 'POST':
        movie = Movie()
        movie.title = request.POST.get('title')
        movie.title_en = request.POST.get('title_en')
        movie.audience = request.POST.get('audience')
        movie.open_date = request.POST.get('open_date')
        movie.genre = request.POST.get('genre')
        movie.watch_grade = request.POST.get('watch_grade')
        movie.score = request.POST.get('score')
        movie.poster_url = request.POST.get('poster_url')
        movie.description = request.POST.get('description')
        movie.save()
        return redirect('movies:detail', movie.pk)
    else:
        return render(request, 'movies/new.html')

def detail(request, pk):
    movie = Movie.objects.get(pk=pk)
    return render(request, 'movies/detail.html', {'movie':movie})

# def edit(request, pk):
#     movie = Movie.objects.get(pk=pk)
#     return render(request, 'movies/edit.html', {'movie':movie})

def update(request, pk):
    movie = Movie.objects.get(pk=pk)
    if request.method == 'POST':
        movie.title = request.POST.get('title')
        movie.title_en = request.POST.get('title_en')
        movie.audience = request.POST.get('audience')
        movie.open_date = request.POST.get('open_date')
        movie.genre = request.POST.get('genre')
        movie.watch_grade = request.POST.get('watch_grade')
        movie.score = request.POST.get('score')
        movie.poster_url = request.POST.get('poster_url')
        movie.description = request.POST.get('description')
        movie.save()
        return redirect('movies:detail', movie.pk)
    else:
        return render(request, 'movies/edit.html', {'movie':movie})

def delete(request, pk):
    movie = Movie.objects.get(pk=pk)
    movie.delete()
    return redirect('movies:index')

lecture_code/DJANGO_BLOG/movies/templates/movies/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>MOVIEs</title>
</head>
<body>
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

lecture_code/DJANGO_BLOG/movies/templates/movies/detail.html
{% extends 'movies/base.html' %}
{% block body %}
    <h1 class='text-center'>{{ movie.title }}</h1>
    <hr>
        <p>제목: {{ movie.title }}</p>
        <p>영문: {{ movie.title_en }}</p>
        <p>관객: {{ movie.audience }}</p>
        <p>개봉: {{ movie.open_date }}</p>
        <p>장르: {{ movie.genre }}</p>
        <p>등급: {{ movie.watch_grade }}</p>
        <p>평점: {{ movie.score }}</p>
        <p>포스터: {{ movie.poster_url }}</p>
        <p>소개: {{ movie.description }}</p>
        <hr>
    <a href="{% url 'movies:update' movie.pk %}"><button class='btn btn-info'>수정</button></a>
    <a href="{% url 'movies:delete' movie.pk %}"><button class='btn btn-warning'>삭제</button></a>
    <a href="{% url 'movies:index' %}"><button class='btn btn-primary'>목록</button></a>
{% endblock %}

lecture_code/DJANGO_BLOG/movies/templates/movies/edit.html
{% extends 'movies/base.html' %}
{% block body %}
<h1 class='text-center'>EDIT</h1>
<hr>
<div class="container">
    <form action="" method="POST">
        {% csrf_token %}
        영화: <input type="text" name="title" value="{{ movie.title }}"> <br>
        영문: <input type="text" name="title_en" value="{{ movie.title_en }}"> <br>
        관객: <input type="number" name="audience" value="{{ movie.audience }}"> <br>
        개봉: <input type="date" name="open_date" value="{{ movie.open_date }}"> <br>
        장르: <input type="text" name="genre" value="{{ movie.genre }}"> <br>
        등급: <input type="text" name="watch_grade" value="{{ movie.watch_grade }}"> <br>
        평점: <input type="number" name="score" value="{{ movie.score }}"> <br>
        포스터: <input type="text" name="poster_url" value="{{ movie.poster_url }}"> <br>
        소개: <textarea name="description" id="" cols="30" rows="10">{{ movie.description }}</textarea> <br>
        <input type="submit" value='입력'>
    </form>
</div>
{% endblock %}

lecture_code/DJANGO_BLOG/movies/templates/movies/index.html
{% extends 'movies/base.html' %}
{% block body %}
<h1 class='text-center'>MOVIE INDEX</h1>
<a href="{% url 'movies:create' %}">[새 영화 등록]</a>
<hr>
{% for movie in movies %}
    <p>No.{{ movie.pk }}: <a href="{% url 'movies:detail' movie.pk %}" >{{ movie.title }}</a>({{ movie.title_en }})</p>
    <hr>
{% endfor %}
{% endblock %}

lecture_code/DJANGO_BLOG/movies/templates/movies/new.html
{% extends 'movies/base.html' %}
{% block body %}
<h1 class='text-center'>NEW MOVIE</h1>
<hr>
<div class="container">
    <form action="" method="POST">
        {% csrf_token %}
        영화: <input type="text" name="title"> <br>
        영문: <input type="text" name="title_en"> <br>
        관객: <input type="number" name="audience"> <br>
        개봉: <input type="date" name="open_date"> <br>
        장르: <input type="text" name="genre"> <br>
        등급: <input type="text" name="watch_grade"> <br>
        평점: <input type="number" name="score"> <br>
        포스터: <input type="text" name="poster_url"> <br>
        소개: <textarea name="description" id="" cols="30" rows="10"></textarea> <br>
        <input type="submit" value='입력'>
    </form>
</div>
{% endblock %}