lecture_code/DJANGO_MOVIE/django_movie/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
]

lecture_code/DJANGO_MOVIE/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('score/<int:movie_id>/',views.score_new, name= 'score_new'),
    path('<int:movie_id>/delete/<int:score_id>/',views.score_delete, name= 'score_delete'),
    path('delete/<int:movie_id>/',views.delete, name= 'delete'),
    path('new/',views.new),
    path('<int:movie_id>/', views.detail, name= 'detail'),
    path('edit/<int:movie_id>/', views.edit, name = 'edit'),
    path('', views.index),
]

lecture_code/DJANGO_MOVIE/movies/models.py
from django.db import models


class Genre(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.id}. 장르:{self.name}' 

class Movie(models.Model):
    title = models.CharField(max_length=20)
    audience = models.IntegerField()
    poster_url = models.TextField()
    description = models.TextField()
    genre_id = models.ForeignKey(Genre, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.id}.{self.title}:{self.content}'


class Score(models.Model):
     content = models.CharField(max_length=140)
     score = models.IntegerField()
     movie_id = models.ForeignKey(Movie, on_delete=models.CASCADE)
        
     def __str__(self):
        return f'{self.id}.{self.score}:{self.movie_id}'
     

lecture_code/DJANGO_MOVIE/movies/views.py
from django.shortcuts import render, redirect
from .models import Movie, Score

def index(request):
    #movie = movie.objects.order_by('open_date')
    movies = Movie.objects.all()[::-1]
    return render(request, 'movies/index.html', {'movies':movies})

def new(request):
    if request.method=='POST':
        title = request.POST.get('title')
        audience =  request.POST.get('audience')
        poster_url = request.POST.get('poster_url')
        description =  request.POST.get('description')
        genre_id = request.POST.get('genre_id')
        movie = Movie(title=title, audience=audience, poster_url=poster_url, description=description) 
        movie.save()
        return redirect('/movies/')
    else : 
        return render(request,'movies/new.html')
#detail 다시보기
def detail(request, movie_id):
    movie = Movie.objects.get(pk=movie_id)
    scores = movie.score_set.all()
    return render(request, 'movies/detail.html',{'movie':movie, 'scores':scores})

def edit(request, movie_id):
    if request.method=='POST':
        movie = Movie.objects.get(pk=movie_id)
        movie.title = request.POST.get('title')
        movie.audience =  request.POST.get('audience')
        movie.poster_url = request.POST.get('poster_url')
        movie.description = request.POST.get('description')
        genre_id = request.POST.get('genre_id')
        movie.save()
        return redirect(f'/movies/{movie.pk}')
    else:
        movie = Movie.objects.get(pk=movie_id)
        return render(request,'movies/edit.html',{'movie':movie})


def delete(request,movie_id):
    movie = Movie.objects.get(pk=movie_id)
    movie.delete()

def score_new(request, movie_id):
    movie = Movie.objects.get(pk= movie_id)
    if request.method =='POST':
        score = Score()
        score.content = request.POST.get('content')
        score.score = request.POST.get('score')
        score.movie_id = movie
        score.save()
        return redirect('movies:detail', movie_id)
    else:
        return redirect('movies:detail', movie_id)

def score_delete(request, movie_id, score_id):
    if request.method == 'POST':
        score = Score.objects.get(pk=score_id)
        score.delete()
    return redirect('movies:detail',movie_id)

lecture_code/DJANGO_MOVIE/movies/templates/movies/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>{%block title %}{% endblock %}Document</title>
</head>
<body>
    <h1 class='text-center'>장고연습</h1>
    <hr>
    <div class="container">
        {% block body %}

        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

lecture_code/DJANGO_MOVIE/movies/templates/movies/detail.html
{% extends 'movies/base.html' %}

{% block title %}영화상세정보{% endblock %}

{% block body %}
    <h1 class = 'text-center'>영화상세정보</h1>
    <h2>{{movie.title}}</h2>
    <hr>
    누적관객수:{{movie.audience}}<br>
    장르:{{movie.genre}}<br>
    평점:{{movie.socre}}<br>
    영화소개:{{movie.poster_url}}<br>
    내용:{{movie.description}}<br>
    <hr>
    <h3>댓글 목록 | 현재 댓글수 : {{scores|length}}</h3>

    {% for score in scores %}

    <div>
        <p style="display:inline;">{{score.score}}</p>
        <form action="{% url 'movies:score_delete' movie.id score.id %}" 
        onclick="return confirm('삭제 하시겠습니까?')" method="POST" style="display:inline;
        text-align: center;">
        {% csrf_token %}
        <button class="btn btn-warning btn-sm">삭제하기</button>
        </form>
        <p>{{score.content}}</p>
    </div>

    <form action="{% url 'movies:score_new' movie.pk %}" method = 'POST'>
        {% csrf_token %}
        한줄평: <input type="text" name='content'>
        평점: <input type="number" name='score'>
        <button class= 'btn btn-success' type = 'submit'>입력</button>
    </form>
    <a href="/movies/">리스트로 가기</a>
    <a href="/movies/edit/{{ movie.pk }}">수정하기</a>

    <a href="/movies/">목록</a>
    <a href="/movies/edit/{{ movie.pk }}">수정</a>
    <form action="/movies/delete/{{ movie.pk }}/" method="POST">
    {% csrf_token %}
    <button>삭제</button>
    </form>
   
    <hr>
    <h3>한줄평</h3><br>
    <ul>
        <li>한줄평: {{score.content}} / 평점{{score.score}} </li>

    </ul>

    {% empty %}
    <p>댓글이 없습니다.</p>
    
    {% endfor %}
    {% endblock %}

lecture_code/DJANGO_MOVIE/movies/templates/movies/edit.html
{% extends 'movies/base.html' %}

{% block title %}편집{% endblock %}

{% block body %}
    <h1 class='text-center'>내용 수정</h1>
    <form action='' method = "POST">
        {% csrf_token %}
        제목:<input type= 'text' name= 'title' value= "{{Movie.title}}"><br>
        누적관객수:<input type= 'text' name= 'audience' value= "{{Movie.title_en}}"><br>
        개봉일자:<input type= 'date' name= 'open_date' value="{{Movie.open_date}}">{{Movie.open_date}}<br>
        포스터링크:<input type= 'text' name= 'poster_url' value="{{Movie.poster_url}}"><br>
        내용:<input type = 'textarea'  name= 'description' id = '' col= 30 low = 10 value="{{Movie.description}}"><br>
        <input type = 'submit'>
    </form>
    <hr>
    <a href='/articles/'>취소하기</a>
{% endblock %}

lecture_code/DJANGO_MOVIE/movies/templates/movies/index.html
{% extends 'movies/base.html' %}

{% block title %}
영화 정보
{% endblock %}

{% block body %}
    <a href="/movies/new">새 영화 등록</a>
    <hr>
    {% for movie in movies %}
    <a href="/movies/{{movie.pk}}">제목:{{movie.title}}</a>
    <P>포스터</P>
    <img src= "{{movie.poster_url}}">
    <hr>
    {% endfor %}
{% endblock %}

lecture_code/DJANGO_MOVIE/movies/templates/movies/new.html
{% extends 'movies/base.html' %}

{% block title %}movie info create{% endblock %}

{% block body %}
    <h1 class='text-center'>NEW</h1>
    <form action='' method = "POST">
        {% csrf_token %}
        제목:<input type= 'text' name= 'title'><br>
        영어 제목:<input type= 'text' name= 'title_en'><br>
        누적관객수:<input type= 'text' name= 'audience'><br>
        개봉일자:<input type= 'text' name= 'open_date'><br>
        장르:<input type= 'text' name= 'genre'><br>
        관람등급"<input type="text" name = 'watch_grade'><br>
        평점:<input type= 'text' name= 'score'><br>
        영화소개:<input type= 'text' name= 'poster_url'><br>
        내용:<input type = 'textarea'  name= 'description' id = '' col= 30 low = 10 ><br>
        <input type = 'submit'>

    </form>
    <hr>
    <a href='/movies/'>뒤로가기</a>
{% endblock %}