lecture_code/DJANGO_BLOG/django_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('jobs/', include('jobs.urls')),
    path('students/', include('students.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lecture_code/DJANGO_BLOG/jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'

urlpatterns = [
    path('', views.index, name='index'),
    path('past_life/', views.past_life, name='past_life'),
]

lecture_code/DJANGO_BLOG/jobs/models.py
from django.db import models

class Job(models.Model):
    name = models.CharField(max_length=20)
    past_job = models.TextField()

    def __str__(self):
        return self.name

lecture_code/DJANGO_BLOG/jobs/views.py
from django.shortcuts import render
from .models import Job
from faker import Faker

def index(request):
    return render(request, 'jobs/index.html')

def past_life(request):
    name = request.POST.get('name')

    # DB에 이름이 있는지 확인
    person = Job.objects.filter(name=name).first()
    # person = Job.objects.get(name=name)

    # DB에 이미 같은 name이 있으면 기존 name의 past_job을 가져오기, (레코드가 있으면 None이 아니니까 True일 것입니다.)
    if person:
        past_job = person.past_job
    else:
        faker = Faker('ko-KR')
        past_job = faker.job()
        person = Job(name=name, past_job=past_job)
        person.save()
    return render(request, 'jobs/past_life.html', {'person':person})

lecture_code/DJANGO_BLOG/jobs/templates/jobs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="container">
        {% block body %}        
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

lecture_code/DJANGO_BLOG/jobs/templates/jobs/index.html
{% extends 'jobs/base.html' %}

{% block body %}
<h1>전생의 직업</h1>
<h2>당신의 전생의 직업을 알려드립니다</h2>

<form action="{% url 'jobs:past_life' %}" method="POST">
    {% csrf_token %}
    <input type="text" name="name">
    <input type="submit" value="입력">
</form>
{% endblock %}

lecture_code/DJANGO_BLOG/jobs/templates/jobs/past_life.html
{% extends 'jobs/base.html' %}

{% block body %}
<h1>{{ person.name }} 님의 전생은 {{ person.past_job }}입니다.</h1>

<a href="{% url 'jobs:index' %}">다시하기</a>
{% endblock %}